mkdir data
wget -P ./data/ http://www.uni-weimar.de/medien/webis/corpora/corpus-wdvc-16/training/wdvc16_meta.csv.7z
wget -P ./data/ http://www.uni-weimar.de/medien/webis/corpora/corpus-wdvc-16/training/wdvc16_truth.csv.7z 
wget -P ./data/ http://www.uni-weimar.de/medien/webis/corpora/corpus-wdvc-16/training/wdvc16_2012_10.xml.7z
wget -P ./data/ http://www.uni-weimar.de/medien/webis/corpora/corpus-wdvc-16/training/wdvc16_2012_11.xml.7z
wget -P ./data/ http://www.uni-weimar.de/medien/webis/corpora/corpus-wdvc-16/training/wdvc16_2013_01.xml.7z
wget -P ./data/ http://www.uni-weimar.de/medien/webis/corpora/corpus-wdvc-16/training/wdvc16_2013_03.xml.7z
wget -P ./data/ http://www.uni-weimar.de/medien/webis/corpora/corpus-wdvc-16/training/wdvc16_2013_05.xml.7z
wget -P ./data/ http://www.uni-weimar.de/medien/webis/corpora/corpus-wdvc-16/training/wdvc16_2013_07.xml.7z
wget -P ./data/ http://www.uni-weimar.de/medien/webis/corpora/corpus-wdvc-16/training/wdvc16_2013_09.xml.7z
wget -P ./data/ http://www.uni-weimar.de/medien/webis/corpora/corpus-wdvc-16/training/wdvc16_2013_11.xml.7z
wget -P ./data/ http://www.uni-weimar.de/medien/webis/corpora/corpus-wdvc-16/training/wdvc16_2014_01.xml.7z
wget -P ./data/ http://www.uni-weimar.de/medien/webis/corpora/corpus-wdvc-16/training/wdvc16_2014_03.xml.7z
wget -P ./data/ http://www.uni-weimar.de/medien/webis/corpora/corpus-wdvc-16/training/wdvc16_2014_05.xml.7z
wget -P ./data/ http://www.uni-weimar.de/medien/webis/corpora/corpus-wdvc-16/training/wdvc16_2014_07.xml.7z
wget -P ./data/ http://www.uni-weimar.de/medien/webis/corpora/corpus-wdvc-16/training/wdvc16_2014_09.xml.7z
wget -P ./data/ http://www.uni-weimar.de/medien/webis/corpora/corpus-wdvc-16/training/wdvc16_2014_11.xml.7z
wget -P ./data/ http://www.uni-weimar.de/medien/webis/corpora/corpus-wdvc-16/training/wdvc16_2015_01.xml.7z
wget -P ./data/ http://www.uni-weimar.de/medien/webis/corpora/corpus-wdvc-16/training/wdvc16_2015_03.xml.7z
wget -P ./data/ http://www.uni-weimar.de/medien/webis/corpora/corpus-wdvc-16/training/wdvc16_2015_05.xml.7z
wget -P ./data/ http://www.uni-weimar.de/medien/webis/corpora/corpus-wdvc-16/training/wdvc16_2015_07.xml.7z
wget -P ./data/ http://www.uni-weimar.de/medien/webis/corpora/corpus-wdvc-16/training/wdvc16_2015_09.xml.7z
wget -P ./data/ http://www.uni-weimar.de/medien/webis/corpora/corpus-wdvc-16/training/wdvc16_2015_11.xml.7z
wget -P ./data/ http://www.uni-weimar.de/medien/webis/corpora/corpus-wdvc-16/training/wdvc16_2016_01.xml.7z
wget -P ./data/test/ http://www.uni-weimar.de/medien/webis/corpora/corpus-wdvc-16/training/wdvc16_2016_05.xml.7z
wget -P ./data/test/ http://www.uni-weimar.de/medien/webis/corpora/corpus-wdvc-16/training/wdvc16_2016_05_meta.csv.7z
wget -P ./data/test/ http://www.uni-weimar.de/medien/webis/corpora/corpus-wdvc-16/training/wdvc16_2016_05_truth.csv.7z
wget -P ./data/validation/ http://www.uni-weimar.de/medien/webis/corpora/corpus-wdvc-16/training/wdvc16_2016_03.xml.7z
wget -P ./data/validation/ http://www.uni-weimar.de/medien/webis/corpora/corpus-wdvc-16/training/wdvc16_2016_03_meta.csv.7z
wget -P ./data/validation/ http://www.uni-weimar.de/medien/webis/corpora/corpus-wdvc-16/training/wdvc16_2016_03_truth.csv.7z
